- id: '1637512236361'
  alias: Doorbell motion
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: fadf699286f2acde3f908ddd912d15a4
    entity_id: binary_sensor.doorbell_motion
    domain: binary_sensor
  condition:
  - type: is_not_open
    condition: device
    device_id: 50dd3a079803fdbf9cc02a40d3535bfd
    entity_id: binary_sensor.front_door_ias_zone
    domain: binary_sensor
  action:
  - device_id: b2bd1c36420bd08fd6d74dc89ee6d882
    domain: mobile_app
    type: notify
    title: Motion!
    message: Motion at the front door
  mode: single
- id: '1637528319451'
  alias: First floor landing motion toggles light
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 41fcce17ced84941794c4d1b6fe29944
    entity_id: binary_sensor.first_floor_landing_motion_sensor_ias_zone
    domain: binary_sensor
  - type: no_motion
    platform: device
    device_id: 41fcce17ced84941794c4d1b6fe29944
    entity_id: binary_sensor.first_floor_landing_motion_sensor_ias_zone
    domain: binary_sensor
  condition:
  - condition: or
    conditions:
    - condition: sun
      after: sunset
    - condition: sun
      before: sunrise
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: '0'
      sequence:
      - type: turn_on
        device_id: adf49dc59ccbe8f52d1e5212ddeb7c67
        entity_id: light.first_floor_landing
        domain: light
    - conditions:
      - condition: trigger
        id: '1'
      sequence:
      - type: turn_off
        device_id: adf49dc59ccbe8f52d1e5212ddeb7c67
        entity_id: light.first_floor_landing
        domain: light
    default: []
  mode: single
- id: '1637795780254'
  alias: Utility room motion
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: b3425071b16708afa34a60fa3fae45b2
    entity_id: binary_sensor.utility_room_camera_motion
    domain: binary_sensor
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: input_select.alarm_backend
      state: disarmed
  action:
  - device_id: b2bd1c36420bd08fd6d74dc89ee6d882
    domain: mobile_app
    type: notify
    title: Motion
    message: Motion in the utility room
  mode: single
- id: '1637941711904'
  alias: Toggle office light on button
  description: ''
  trigger:
  - device_id: bad273a6abaf8e9ae53f8fcab5f9bdc7
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button
  condition: []
  action:
  - type: toggle
    device_id: 4e0c040559541c6028fd8f136533af64
    entity_id: light.office
    domain: light
  mode: single
- id: '1638012889108'
  alias: Pause TV on doorbell
  description: ''
  trigger:
  - type: occupied
    platform: device
    device_id: fadf699286f2acde3f908ddd912d15a4
    entity_id: binary_sensor.doorbell_ding
    domain: binary_sensor
  condition: []
  action:
  - service: media_player.media_pause
    target:
      entity_id:
      - media_player.living_room_tv
      - media_player.lg_webos_smart_tv
  mode: single
- id: '1638022677865'
  alias: Toggle bathroom light on door
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: 75160a9c6ad03e30b2a880c835b8ce87
    entity_id: binary_sensor.bathroom_door_ias_zone
    domain: binary_sensor
  condition:
  - condition: or
    conditions:
    - condition: sun
      before: sunrise
    - condition: sun
      after: sunset
  action:
  - type: toggle
    device_id: eca79d9063ef5334677a5b7bc1bc7462
    entity_id: light.bathroom
    domain: light
  mode: single
- id: '1638126598008'
  alias: Hallway motion toggles light
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: bc771174774c3944817716ad44b5fbf5
    entity_id: binary_sensor.hallway_motion_sensor_ias_zone
    domain: binary_sensor
  - type: no_motion
    platform: device
    device_id: bc771174774c3944817716ad44b5fbf5
    entity_id: binary_sensor.hallway_motion_sensor_ias_zone
    domain: binary_sensor
  condition:
  - condition: or
    conditions:
    - condition: sun
      before: sunrise
    - condition: sun
      after: sunset
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: '0'
      sequence:
      - type: turn_on
        device_id: 4249e30661fde924eeb48a912cdc4222
        entity_id: light.hallway
        domain: light
    - conditions:
      - condition: trigger
        id: '1'
      sequence:
      - type: turn_off
        device_id: 4249e30661fde924eeb48a912cdc4222
        entity_id: light.hallway
        domain: light
    default: []
  mode: single
- id: '1638228796752'
  alias: Start vacuum
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: c00856b7fd8d7d2083eacfcc5ef7c65e
    entity_id: switch.home_occupied
    domain: switch
  - platform: time
    at: '12:00'
  condition:
  - condition: state
    entity_id: vacuum.n97s
    state: 'off'
  action:
  - service: vacuum.turn_on
    target:
      entity_id: vacuum.n97s
  mode: single
- id: '1638532171395'
  alias: Toggle living room lights with button
  description: ''
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: 00:15:8d:00:07:5e:20:16
      command: single
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: 00:15:8d:00:07:5e:20:16
      command: hold
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: 00:15:8d:00:07:5e:20:16
      command: double
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: '0'
      sequence:
      - service: light.toggle
        target:
          area_id: living_room
    - conditions:
      - condition: trigger
        id: '1'
      sequence:
      - service: switch.toggle
        target:
          entity_id: switch.flux
    - conditions:
      - condition: trigger
        id: '2'
      sequence:
      - service: light.toggle
        target:
          entity_id:
          - light.living_room_1
          - light.living_room_2
    default: []
  mode: single
- id: '1638533239853'
  alias: Second floor motion toggles light
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 69ea1fc6ce42a183e6b6e2eba42626a3
    entity_id: binary_sensor.second_floor_landing_motion_sensor_ias_zone
    domain: binary_sensor
  - type: no_motion
    platform: device
    device_id: 69ea1fc6ce42a183e6b6e2eba42626a3
    entity_id: binary_sensor.second_floor_landing_motion_sensor_ias_zone
    domain: binary_sensor
  condition:
  - condition: or
    conditions:
    - condition: sun
      before: sunrise
    - condition: sun
      after: sunset
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: '0'
      sequence:
      - type: turn_on
        device_id: 2e40e376f12264fe37a73a9a167aa3e8
        entity_id: light.second_floor_landing_light_level_on_off
        domain: light
    - conditions:
      - condition: trigger
        id: '1'
      sequence:
      - type: turn_off
        device_id: 2e40e376f12264fe37a73a9a167aa3e8
        entity_id: light.second_floor_landing_light_level_on_off
        domain: light
    default: []
  mode: single
- id: '1638545111881'
  alias: Start washing timer on button press
  description: ''
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: 00:12:4b:00:25:20:cf:e0
      command: toggle
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: 00:12:4b:00:25:20:cf:e0
      command: 'on'
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: '0'
      sequence:
      - service: timer.start
        data:
          duration: '5400'
        target:
          entity_id: timer.washing
    - conditions:
      - condition: trigger
        id: '1'
      sequence:
      - service: timer.start
        data:
          duration: '2100'
        target:
          entity_id: timer.washing
    default: []
  mode: single
- id: '1638545636241'
  alias: Alert on washing timer finished
  description: ''
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.washing
  condition: []
  action:
  - service: media_player.turn_on
    target:
      entity_id: media_player.dashboard
  - service: media_player.volume_set
    target:
      entity_id: media_player.dashboard
    data:
      volume_level: 1
  - service: tts.cloud_say
    data:
      entity_id: media_player.2dc548bb_f9947ee0
      message: The washing machine timer has finished
      cache: true
  mode: single
- id: '1638552396252'
  alias: Toggle heating when occupancy changes
  description: ''
  trigger:
  - platform: state
    entity_id: group.residents
    from: home
    to: not_home
  - platform: state
    entity_id: group.residents
    from: not_home
    to: home
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: '0'
      sequence:
      - type: turn_off
        device_id: 7ce45ebf897d77d6216384886f8946b2
        entity_id: switch.living_room_thermostat
        domain: switch
    - conditions:
      - condition: trigger
        id: '1'
      sequence:
      - type: turn_on
        device_id: 7ce45ebf897d77d6216384886f8946b2
        entity_id: switch.living_room_thermostat
        domain: switch
    default: []
  mode: single
- id: '1638552396252'
  alias: Heating on when occupied
  description: ''
  trigger:
  - platform: state
    entity_id: group.residents
    from: not_home
    to: home
  condition:
  - condition: state
    entity_id: binary_sensor.temp_below_target
    state: 'on'
  action:
  - type: turn_on
    device_id: 7ce45ebf897d77d6216384886f8946b2
    entity_id: switch.living_room_thermostat
    domain: switch
  mode: single
- id: '1638701607270'
  alias: Arm alarm on door close
  description: ''
  trigger:
  - type: not_opened
    platform: device
    device_id: 50dd3a079803fdbf9cc02a40d3535bfd
    entity_id: binary_sensor.front_door_ias_zone
    domain: binary_sensor
  condition:
  - condition: state
    entity_id: alarm_control_panel.alarm_frontend
    state: armed_away
  - condition: state
    entity_id: input_select.alarm_backend
    state: disarmed
  action:
  - service: input_select.select_option
    target:
      entity_id: input_select.alarm_backend
    data:
      option: arm_away
  mode: single
- id: '1638701880950'
  alias: Disarm alarm on code entry
  description: ''
  trigger:
  - platform: state
    entity_id: alarm_control_panel.alarm_frontend
    from: armed_away
    to: disarmed
  condition: []
  action:
  - service: input_select.select_option
    target:
      entity_id: input_select.alarm_backend
    data:
      option: disarmed
  mode: single
- id: '1638707231699'
  alias: Alert on motion
  description: ''
  trigger:
  - platform: state
    entity_id: group.motion_sensors
    from: 'off'
    to: 'on'
  - type: motion
    platform: device
    device_id: b3425071b16708afa34a60fa3fae45b2
    entity_id: binary_sensor.utility_room_camera_motion
    domain: binary_sensor
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: input_select.alarm_backend
      state: disarmed
  action:
  - service: notify.phones
    data:
      message: Motion has been detected at home
      title: Alarm
  mode: single
